services:
  flexbit-frontend:
    container_name: flexbit-frontend
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_MIDTRANS_CLIENT_KEY: ${NEXT_PUBLIC_MIDTRANS_CLIENT_KEY}
    image: flexbit-frontend:1.0.0
    env_file:
      - .env
    restart: unless-stopped
    cpus: 0.5
    mem_limit: 512m
    mem_reservation: 256m
    networks:
      - flexeet-network

networks:
  flexeet-network:
    external: true
